name: build
on:
  push:
    paths:
      - '**/*.ts'
      - '**/*.js'
      - '**/*.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - run: yarn test
      - run: yarn dev:package
