name: build
on:
  push:
    paths-ignore:
      - 'CHANGELOG.md'
      - '.github/workflows/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - run: yarn test
      - run: yarn dev:package:bakcend
      - run: yarn dev:package:datalake
