name: build
on:
  push:
    paths-ignore:
      - 'CHANGELOG.md'
      - '.github/workflows/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set credentials
        run: |
          aws configure set region ap-northeast-2
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws --profile aa configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws --profile aa configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: deptno/action-aws-ssm-to-dotenv@v1.3.1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-2
        with:
          ssm-path: /deptno/abandoned-animals/dev
          format: yaml
          output: packages/aa_backend/env.dev.yml
          prefix: AA_
      - run: cp packages/aa_backend/env.dev.yml packages/aa_datalake/env.dev.yml
      - name: count env
        run: wc -l packages/aa_backend/env.dev.yml
      - run: yarn
      - run: yarn test
      - run: yarn dev:package:backend
      - run: yarn dev:package:datalake
